---
title: "Schedule (subject to change)"
subtitle: "WILD3810: Plant and animal populations"
author: "Spring 2020"
output: 
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Schedule}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

# LECTURE SCHEDULE 

```{r lecture_schedule, echo = FALSE}
library(kableExtra)
schedule <- data.frame(Week = c("1 (Jan. 18 & 20)", "2 (Jan. 25 & 27)", "3 (Feb. 1 & 3)", "4 (Feb. 8 & 10)",
                                "5 (Feb. 15 & 17)", "6 (Feb. 22 & 24)", "7 (Mar. 1 & 3)", "8 (Mar. 8 & 10)",
                                "9 (Mar. 15 & 17)", "10 (Mar. 22 & 24)", "11 (Mar. 29 & 31)", "12 (Apr. 5 & 7)",
                                "13 (Apr. 12 & 14)", "14 (Apr. 19 & 21)", "15 (Apr. 26 & 28)"),
                       M = c("No class", # Jan 18
                             "Abundance", # Jan 25
                             "Density-independent population growth", # Feb 1
                             "Density-dependent population growth", #Feb 8
                             "President's Day - no class", # Feb 15
                             "Exam 1", # Feb 22
                             "Life tables", # Mar 1
                             "Reproduction", # Mar 8
                             "Matrix models (continued)", # Mar 15
                             "Sensitivity and elasticity", # Mar 22
                             "Review", # Mar 29
                             "Review Exam 2", # Apr 5
                             "Metapopulation dynamics (continued)", # Apr 12
                             "Competition", # Apr 19
                              "Review" #Apr 26
                             ),
                       W = c("Intro to WILD3810", # Jan 20
                             "Abundance (continued)", # Jan 27
                              "Stochastic population dynamics", # Feb 3
                              "Dynamics of small populations", # Feb 10
                               "Buffer", # Feb 17
                              "Review Exam 1", # Feb 24
                              "Survival estimation", # Mar 3
                             "Matrix models", # Mar 10
                             "Age-structured dynamics", # Mar 17
                              "Life-history diversity", # Mar 24
                             "Exam 2", # Mar 31
                             "Metapopulation dynamics", # Apr 7
                             "Source-sink dynamics", # Apr 14
                             "Predator-prey dynamics", # Apr 21
                             "No class" # Apr 28
                             ))

schedule %>%
  kable("html", col.names = c("Week (dates)", "M", "W"), align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = TRUE) %>%
  add_header_above(c("", "Lecture" = 2))  %>%
  group_rows("Unit 1: Dynamics of unstructured populations", 1,6, label_row_css = "background-color: #333333; color: #eeeeee;") %>%
  group_rows("Unit 2: Dynamics of structured populations", 7,11, label_row_css = "background-color: #333333; color: #eeeeee;") %>%
  group_rows("Unit 3: Spatial dynamics", 12, 13, label_row_css = "background-color: #333333; color: #eeeeee;") %>%
  group_rows("Unit 4: Species interactions", 14, 15, label_row_css = "background-color: #333333; color: #eeeeee;")

```

# LAB SCHEDULE
```{r lab_schedule, echo = FALSE}
library(kableExtra)
labs <- data.frame(Week = c("1 (Jan. 18)", "2 (Jan. 25)", "3 (Feb. 1)", "4 (Feb. 8)",
                                "5 (Feb. 15)", "6 (Feb. 22)", "7 (Mar. 1)", "8 (Mar. 8)",
                                "9 (Mar. 15)", "10 (Mar. 22)", "11 (Mar. 29)", "12 (Apr. 5)",
                                "13 (Apr. 12)", "14 (Apr. 19)", "15 (Apr. 26)"),
                   Topic = c("No lab", #1
                             "Introduction to R/R Markdown", #2
                             "Introduction to R (cont.)/Abundance estimation", #3
                             "Introduction to R/Modeling population growth", #4
                             "President's Day - no lab", #5
                             "Modeling population growth (continued)", #6
                             "Population viability analysis", #7
                             "Life tables", #8
                             "Survival estimation", #9 
                             "Matrix population projections", #10 
                             "Elasticity analysis and comparison of life history strategies", #11
                             "Metapopulation models", #12
                             "Occupancy models", #13
                             "Compensatory predation", #14
                             "No lab"))

labs %>%
  kable("html", col.names = c("Week (date)", "Topic"), align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = TRUE) %>%
  group_rows("Unit 1: Dynamics of unstructured populations", 1,6, label_row_css = "background-color: #333333; color: #eeeeee;") %>%
  group_rows("Unit 2: Dynamics of structured populations", 7,11, label_row_css = "background-color: #333333; color: #eeeeee;") %>%
  group_rows("Unit 3: Spatial dynamics", 12, 13, label_row_css = "background-color: #333333; color: #eeeeee;") %>%
  group_rows("Unit 4: Species interactions", 14, 15, label_row_css = "background-color: #333333; color: #eeeeee;")

```
