---
title: "Lecture 0"
subtitle: "Course overview"
author: "<br/><br/><br/>WILD3810 (Spring 2019)"
output:
  xaringan::moon_reader:
    css: ["default", "WILD3810.css", "WILD3810-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include = FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE, fig.align = 'center', warning=FALSE, message=FALSE)
library(WILD3810)
# library(gganimate)
```


# LOGISTICS

**Lecture**: Monday and Wednesday 10:30-11:20 BNR 314  
**Lab**: Monday 2:30-4:20 QLIB 306  
**Credits**: 3  

---
# INSTRUCTORS

#### Dr. Clark Rushing  
[clark.rushing@usu.edu](clark.rushing@usu.edu)   
**Office**: NR 146   
**Office hours**: Monday and Wednesday 1:00-2:30 (or by appointment)  

#### Lauren Ricci (TA)  
[lauren.e.ricci@gmail.com](lauren.e.ricci@gmail.com)   
**Office**: NR 233   
**Office hours**: Thursday 10:30-12:30 (or by appointment)


---
# COURSE FORMAT

Refer to [syllabus](https://rushinglab.github.io/WILD3810/articles/syllabus.html)

---
# COURSE OBJECTIVES

--
1) Understand general concepts of plant & animal population dynamics  
<br/>

--
2) Gain experience using mathematics and computer software to examine dynamics of plant and animal populations  
<br/>

--
3) Apply the following skills learned to other classes:  
  + Data entry  
  + Application of basic statistical tests  
  + Graphical presentation of data and statistical results  


--
4) Analyze data and use models to project future plant & animal population conditions resulting from management or anthropogenic disturbances  
<br/>

--
5)	Further refine quantitative and critical thinking skills  
